version: "3.5"
services:
  centos7php74dev:
    build:
      context: dev
      args:
        centos: $OS7
    image: "aursu/php74build:${OS7TAG}-dev"
  centos8php74dev:
    build:
      context: dev
      args:
        centos: $OS8
    image: "aursu/php74build:${OS8TAG}-dev"