version: "3.5"
services:
  centos7php74run:
    build:
      context: .
      args:
        centos: $OS7
    image: "aursu/php74build:${OS7TAG}-runtime"
  centos7php74devbase:
    build:
      context: .
      args:
        image: nodedev
        centos: $OS7
    image: "aursu/php74build:${OS7TAG}-devbase"
