version: "3.5"
services:
  centos7php74run:
    build:
      context: .
    image: aursu/php74build:7-runtime
  centos7php74devbase:
    build:
      context: .
      args:
        image: 7-nodedev
    image: aursu/php74build:7-devbase
