version: "3.5"
services:
  centos7php74dev:
    build:
      context: dev
    image: aursu/php74build:7-dev
  centos8php74dev:
    build:
      context: dev
      args:
        image: 8-devbase
    image: aursu/php74build:8-dev