version: "3.5"
services:
  centos8php74run:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
    image: "aursu/php74build:${OS8TAG}-runtime"
  centos8php74devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: nodedev
        centos: $OS8
    image: "aursu/php74build:${OS8TAG}-devbase"