version: "3.5"
services:
  centos8php74run:
    build:
      context: .
      dockerfile: Dockerfile.el8
    image: aursu/php74build:8-runtime
  centos8php74devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: 8-nodedev
    image: aursu/php74build:8-devbase
